#!/bin/bash

set -e
USERNAME=madmin

echo UPDATE

apt remove -y bluez bluez-firmware ntfs-3g alsa* fakeroot ethtool libsound* nfs-common wget xxd

apt-get autoremove -y
apt-get purge -y
apt-get clean

apt update
apt upgrade -y
sleep 3
apt install -y mc htop mtr-tiny ufw

apt-get autoremove -y
apt-get purge -y
apt-get clean

timedatectl set-timezone Europe/Warsaw

echo CONFIG FILES
cat << EOFenv > /etc/environment
LC_ALL=en_GB.UTF-8
LANG=en_GB.UTF-8
EOFenv

cat << EOFrc > /etc/rc.local
#!/bin/sh -e
# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

dphys-swapfile swapoff
/usr/bin/tvservice -o
sleep 1
iw wlan0 set txpower fixed 2100
exit 0
EOFrc


# cat << EOFwpa > /etc/wpa_supplicant/
# ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
# update_config=1
# country=PL

# network={
#         ssid="NetworkSSID"
#         psk="password"
# }
# EOFwpa

cat << EOFov >> /boot/config.txt
arm_freq=1100
arm_freq_min=800
over_voltage=4
sdram_freq=500
sdram_over_voltage=2
boot_delay=1
dtparam=audio=off
gpu_mem=16
dtoverlay=pi3-disable-bt
dtparam=sd_overclock=50
EOFov

cat << EOFssh > /etc/ssh/sshd_config
Port 29880
LogLevel INFO
LoginGraceTime 30s
MaxAuthTries 2
MaxSessions 2
PermitRootLogin no
ChallengeResponseAuthentication no
UsePAM yes
AcceptEnv LANG LC_*
Subsystem       sftp    /usr/lib/openssh/sftp-server
EOFssh

cat << EOFnet >> /etc/dhcpcd.conf
interface wlan0
static ip_address=192.168.50.101/24
static routers=192.168.50.100
static domain_name_servers=192.168.50.100
EOFnet

echo USER ADD
useradd -m -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi,docker $USERNAME
# passwd madmin
userdel -r pi

cat << EOFnano > /home/madmin/.selected_editor
# Generated by /usr/bin/select-editor
SELECTED_EDITOR="/bin/nano"
EOFnano

# echo " cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1" >> /boot/cmdline.txt
# reboot

# echo Install Docker
# curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
# chmod +x /tmp/get-docker.sh
# sh /tmp/get-docker.sh

# https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal-and-alpine-3-13
# https://github.com/nextcloud/docker/issues/1589
# https://launchpad.net/ubuntu/bionic/+package/libseccomp2

# [Service]
# ExecStart=
# ExecStart=/usr/sbin/dockerd --experimental=true

echo DONE